import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header/page'
import Footer from './footer/page'
import NextAuthProvider from '@/component/Providers'
import Head from 'next/head';
import { Providers } from "@/redux/provider";
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Hello Next js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={`${inter.className}`}>
        <Providers>
          <NextAuthProvider>

            <Header />
            <div className='mb-20'>
              {children}
            </div>
            <Footer />
          </NextAuthProvider>
        </Providers>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js" async />
      </body>
    </html>
  )
}
